query Issues($pageSize: Int!, $after: String, $updatedAtFrom: DateTime) {
  issues(first: $pageSize, orderBy: updatedAt, after: $after,filter: { 
    updatedAt: { gte: $updatedAtFrom }
  }) {
    edges {
      node {
        id
        title
        description
        priority
        url
        state {
          id
          name
        }
        history {
          nodes {
            actor {
              id
            }
            createdAt
            fromState {
              id
              name
            }
            toState {
              id
              name
            }
          }
        }
        startedAt
        parent {
          id
        }

        assignee {
          id
          name
          createdAt
        }
        createdAt
        updatedAt
        labels {
          nodes {
            id
            name
          }
        }
        project {
          id
          name
        }
        cycle {
          id
        }
        creator {
          id
        }
      }
      cursor
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
