query Issue($id: String!) {
  issue(id: $id) {
    id
    title
    description
    priority
    url
    state {
      id
      name
    }
    history {
      nodes {
        actor {
          id
        }
        createdAt
        fromState {
          id
          name
        }
        toState {
          id
          name
        }
      }
    }
    startedAt
    parent {
      id
    }

    assignee {
      id
      name
    }
    createdAt
    updatedAt
    labels {
      nodes {
        id
        name
      }
    }
    project {
      id
      name
    }
  }
}
