query Teams {
  teams {
    nodes {
      id
      name
      description
      createdAt
      updatedAt
      members {
        nodes {
          id
        }
      }
      issues {
        nodes {
          id
        }
      }
    }
  }
}
