mutation MyMutation {
  insert_vcs_Repository_one(
    object: {
      uid: "uid", 
      name: "asdgasgasffffffffg",
      vcs_Organization: {
        data: {
          source: "source", 
          uid: "orguid",
          name: "sgsgdssgdg"
        },
        on_conflict: {
          constraint: vcs_Organization_pkey, 
          update_columns: [name, refreshedAt]
        }
      }
    }, 
    on_conflict: {
      constraint: vcs_Repository_pkey,
      update_columns: [name, refreshedAt]
    }
  ) {
    uid
    organization
    vcs_Organization {
      uid
    }
  }
}