query cicdArtifactQueryByRepoName($repoNames: [String], $limit: Int) {
  cicd_Artifact(
    where: {repository: {uid: {_in: $repoNames}}}
    limit: $limit
  ) {
    uid
    repository {
      organization {
        uid
        source
      }
      uid
    }
  }
}
