query cicdArtifactQueryByCommitSha($commitSha: String) {
  cicd_Artifact(where: {uid: {_eq: $commitSha}}, distinct_on: uid) {
    uid
    repository {
      organization {
        uid
        source
      }
      uid
    }
  }
}
