query vcsRepositoryQuery($vcsRepoNames: [String], $limit: Int) {
  vcs_Repository(where: {name: {_in: $vcsRepoNames}}, limit: $limit, distinct_on: name) {
    organization {
      uid
      source
    }
    name
  }
}
