query listUsers($pageSize: Int! = 100, $offset: Int! = 0, $queryConditions: String! = "") {
  GlideRecord_Query {
    sys_user(pagination: {limit: $pageSize, offset: $offset}, queryConditions: $queryConditions) {
      _results {
        sys_id {
          value
        }
        name {
          value
        }
        email {
            value
        }
        sys_updated_on {
          value
        }
      }
    }
  }
}
