query getTestExecutions(
  $modifiedSince: String
  $start: Int,
  $limit: Int!,
) {
  getTestExecutions(
    start: $start,
    limit: $limit,
    modifiedSince: $modifiedSince
  ) {
    total
    start
    limit
    results {
      issueId
      lastModified
      testEnvironments
      jira(fields: ["key", "description", "summary", "labels"])
    }
  }
}
