// Generated by https://quicktype.io

export interface Worker {
  readonly primaryJob: Job;
  readonly person: PersonRef;
  readonly additionalJobs: ReadonlyArray<Job>;
  readonly descriptor: string;
  readonly id: string;
}

export interface Job {
  readonly businessTitle: string;
  readonly supervisoryOrganization: JobProfile;
  readonly jobType: JobType;
  readonly jobProfile: JobProfile;
  readonly location: Location;
  readonly workSpace: WorkSpace;
  readonly descriptor: string;
  readonly id: string;
}

export interface JobProfile {
  readonly descriptor: string;
  readonly id: string;
}

export interface JobType {
  readonly descriptor: string;
}

export interface Location {
  readonly country: JobType;
  readonly id: string;
  readonly descriptor: string;
}

export interface WorkSpace {
  readonly locationChain: string;
  readonly descriptor: string;
  readonly id: string;
}

export interface PersonRef {
  readonly phone: string;
  readonly email: string;
  readonly id: string;
}

export interface Person {
  readonly photos: string;
  readonly homeEmails: string;
  readonly personalInformation: string;
  readonly homeWebAddresses: string;
  readonly universal_ID: UniversalID;
  readonly workInstantMessengers: string;
  readonly homePhones: string;
  readonly preferredName: string;
  readonly workEmails: string;
  readonly workAddresses: string;
  readonly workWebAddresses: string;
  readonly homeAddresses: string;
  readonly legalName: string;
  readonly socialNetworks: string;
  readonly workPhones: string;
  readonly additionalNames: string;
  readonly homeInstantMessengers: string;
  readonly id: string;
  readonly href: string;
}

export interface UniversalID {
  readonly id: string;
}

export interface SupervisoryOrganization {
  readonly name: string;
  readonly managers: ReadonlyArray<Manager>;
  readonly code: string;
  readonly inactive: boolean;
  readonly descriptor: string;
  readonly id: string;
}

export interface Manager {
  readonly id: string;
  readonly descriptor: string;
}

export interface SupervisoryOrganizationMember {
  readonly location: Location;
  readonly businessTitle: string;
  readonly worker: JobProfile;
  readonly supervisoryOrganization: JobProfile;
  readonly nextPayPeriodStartDate: string;
  readonly jobType: JobType;
  readonly jobProfile: JobProfile;
  readonly descriptor: string;
  readonly id: string;
}

export interface SupervisoryOrganizationOrgChart {
  readonly superior: Superior;
  readonly subordinates: ReadonlyArray<Superior>;
  readonly descriptor: string;
  readonly id: string;
}

export interface Superior {
  readonly name: string;
  readonly managers: ReadonlyArray<Manager>;
  readonly code: string;
  readonly inactive: boolean;
  readonly descriptor: string;
  readonly id: string;
}
