query jobsQuery($maxJobsPerBuild: Int,$after: String) {
  viewer {
    jobs(first: $maxJobsPerBuild,after: $after) { 
       edges{
        node
        { 
           __typename
                  ... on JobTypeCommand {
                    uuid
                    build()
                    {
                      uuid
                      pipeline()
                      {
                        slug
                        organization()
                        {
                          slug
                        }
                      }
                    }
                    label
                    state
                    createdAt
                    finishedAt
                    startedAt
                    url
                    command
                  }
                  ... on JobTypeBlock {
                    uuid
                    build()
                    {
                      uuid
                      pipeline()
                      {
                        slug
                        organization()
                        {
                          slug
                        }
                      }
                    }
                    state
                    label
                    unblockedAt
                  }
                  ... on JobTypeWait {
                    uuid
                    build()
                    {
                      uuid
                      pipeline()
                      {
                        slug
                        organization()
                        {
                          slug
                        }
                      }
                    }
                    state
                    label
                  }
                  ... on JobTypeTrigger {
                    uuid
                    build()
                    {
                      uuid
                      pipeline()
                      {
                        slug
                        organization()
                        {
                          slug
                        }
                      }
                    }
                    state
                    label
                    triggered {
                      startedAt
                      createdAt
                      finishedAt
                    }
                  } 
        },
        cursor
      }
      pageInfo{
          hasNextPage
          endCursor
        }
    }
    }
  }
