query pipelineBuildsQuery($slug: ID!, $pageSize: Int!, $createdAtFrom: DateTime, $after: String,$maxJobsPerBuild: Int) {
  pipeline(slug: $slug) { 
      builds(first: $pageSize, createdAtFrom: $createdAtFrom, after: $after) {
        edges {
          node {
             id
            uuid
            pipeline {
              slug
              repository {
                url
                provider {
                  name
                }
              }
              organization {
                slug
              }
            }
            message
            number
            createdAt
            startedAt
            finishedAt
            state
            url
            commit
            jobs(first: $maxJobsPerBuild) {
              edges {
                node {
                  __typename
                  ... on JobTypeCommand {
                    uuid
                    label
                    state
                    createdAt
                    finishedAt
                    startedAt
                    url
                    command
                  }
                  ... on JobTypeBlock {
                    uuid
                    state
                    label
                    unblockedAt
                  }
                  ... on JobTypeWait {
                    uuid
                    state
                    label
                  }
                  ... on JobTypeTrigger {
                    uuid
                    state
                    label
                    triggered {
                      startedAt
                      createdAt
                      finishedAt
                    }
                  }
                }
              }
            }
          }
          cursor
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
}
