query pipelinesQuery($slug: ID!, $pageSize: Int!, $after: String) {
  organization(slug: $slug) {
      pipelines(first: $pageSize, after: $after){
        edges{
          node {
            id
            organization {
              slug
            }
            uuid
            name
            slug
            url
            createdAt
            description
            repository {
              url
              provider {
                name
              }
            }
          }
          cursor
        }
        pageInfo{
          hasNextPage
          endCursor
        }
      }
    }
}
