query buildsQuery($maxBuilds: Int){
  viewer {
    builds(first:$maxBuilds) {
       count,
       pageInfo {
         endCursor
         startCursor
       },
       edges{
        node
        {
            id
            uuid
            pipeline()
            {
              slug
              repository {
                url
                provider {
                  name
                } 
              }
              organization()
              {
                slug
              }
            }
            message
            number
            createdAt
            startedAt
            finishedAt
            state
            url
            commit
        }
      }
      
    }
  }
}
