query jobsQuery($maxJobsPerBuild: Int) {
  viewer {
    jobs(first: $maxJobsPerBuild) { 
       edges{
        node
        { 
           __typename
                  ... on JobTypeCommand {
                    uuid
                    label
                    state
                    createdAt
                    finishedAt
                    startedAt
                    url
                    command
                  }
                  ... on JobTypeBlock {
                    uuid
                    state
                    label
                    unblockedAt
                  }
                  ... on JobTypeWait {
                    uuid
                    state
                    label
                  }
                  ... on JobTypeTrigger {
                    uuid
                    state
                    label
                    triggered {
                      startedAt
                      createdAt
                      finishedAt
                    }
                  } 
        }
      }
    }
    }
  }
 

 