query pipelineBuildsQuery($slug: ID!, $pageSize: Int!, $maxJobsPerBuild: Int!, $createdAtFrom: DateTime, $after: String) {
  pipeline(slug: $slug) {
      id
      uuid
      slug
      name
      url
      description
      repository {
        url
        provider {
          name
        }
      }
      builds(first: $pageSize, createdAtFrom: $createdAtFrom, after: $after) {
        edges {
          node {
            uuid
            message
            number
            createdAt
            startedAt
            finishedAt
            state
            url
            commit
            jobs(first: $maxJobsPerBuild) {
              edges {
                node {
                  __typename
                  ... on JobTypeCommand {
                    uuid
                    label
                    state
                    createdAt
                    finishedAt
                    startedAt
                    url
                    command
                  }
                  ... on JobTypeBlock {
                    uuid
                    state
                    label
                    unblockedAt
                  }
                  ... on JobTypeWait {
                    uuid
                    state
                    label
                  }
                  ... on JobTypeTrigger {
                    uuid
                    state
                    label
                    triggered {
                      startedAt
                      createdAt
                      finishedAt
                    }
                  }
                }
              }
            }
          }
          cursor
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
}