query pipelinesQuery($slug: ID!, $pageSize: Int!, $after: String,$createdAtFrom: DateTime) {
  organization(slug: $slug) {
      pipelines(first: $pageSize, after: $after,createdAtFrom: $createdAtFrom){
        edges{
          node {
            id
            organization()
            {
              id
            }
            uuid
            name
            slug
            url
            createdAt
            description
            repository {
              url
              provider {
                name
              }
            }
          }
          cursor
        }
        pageInfo{
          hasNextPage
          endCursor
        }
      }
    }
} 