connector_image: example-source
tests:
  spec:
    - spec_path: "test_files/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "test_files/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "test_files/configured_catalog.json"
