# query organizationsQuery($pageSize: Int!, $after: String) {
#   viewer {
#     organizations(first: $pageSize, after: $after) {
#       edges {
#         cursor
#         node {
#           id
#           name
#           slug
#         }
#       }
#       pageInfo {
#         hasNextPage
#         endCursor
#       }
#     }
#   }
# }
