query pipelinesQuery($slug: ID!, $pageSize: Int!, $after: String) {
  organization(slug: $slug) {
      pipelines(first: $pageSize, after: $after){
        edges{
          node {
            id
            uuid
            name
            slug
            url
            description
            repository {
              url
              provider {
                name
              }
            }
          }
          cursor
        }
        pageInfo{
          hasNextPage
          endCursor
        }
      }
    }
}


# query organizationsQuery($pageSize: Int!, $after: String) {
#   viewer {
#     organizations(first: $pageSize, after: $after) {
#       edges {
#         cursor
#         node {
#           id
#           name
#           slug

#           pipelines(first: $pageSize, after: $after) {
#             edges {
#               cursor
#               node {
#                 id
#                 name
#                 slug
#                 description
#                 createdAt
#                 url
                
#                 builds(first: $pageSize, after: $after) {
#                   edges {
#                     cursor
#                     node {
#                       uuid
                      
#                       source {
#                         name
#                       }
#                       message
#                       metaData {
#                         edges {
#                           node {
#                             key
#                             value
#                           }
#                         }
#                       }
                      
#                       number
#                       state
#                       url
#                       commit
#                       createdAt
#                       startedAt
#                       finishedAt
                      
#                       jobs(first: $pageSize, after: $after) {
#                         edges {
#                           cursor
#                           node {
#                             __typename
#                             ... on JobTypeCommand {
#                               uuid
#                               label
#                               state
#                               createdAt
#                               finishedAt
#                               startedAt
#                               url
#                               command
#                             }
#                             ... on JobTypeBlock {
#                               uuid
#                               state
#                               label
#                               unblockedAt
#                             }
#                             ... on JobTypeWait {
#                               uuid
#                               state
#                               label
#                             }
#                             ... on JobTypeTrigger {
#                               uuid
#                               state
#                               label
#                               triggered {
#                                 startedAt
#                                 createdAt
#                                 finishedAt
#                               }
#                             }
#                           }
#                         }
#                         pageInfo {
#                           hasNextPage
#                           endCursor
#                         }
#                       }
#                     }
#                   }
#                   pageInfo {
#                     hasNextPage
#                     endCursor
#                   }
#                 }
#               }
#             }
#             pageInfo {
#               hasNextPage
#               endCursor
#             }
#           }
#         }
#       }
#       pageInfo {
#         hasNextPage
#         endCursor
#       }
#     }
#   }
# }
