query {
  findings(offset: 100, first: 50, q: "tool_name in (\"codeql\") ") {
    edges {
      node {
        repository {
          id
          uid
        }
        toolName
        dbCreatedAt
        dbUpdatedAt
        scannerCreatedAt
        scannerUpdatedAt
        businessRisk
        dismissReason
        dismissedAt
        scannerDismissedAt
        userDueDate
        sourceFilename
        sourcePath
        vulnerableVersion
        vulnerability {
          severity
          cve
          ghsa
          fixAvailable
        }
        status
        scannerStatus
        userUpdatedStatus
        line
        jiraUrl
        lastReviewed
        scannerConfidence
        asset {
          name
          id
          uid
          type
          description
        }
        projects
        key

        dbCreatedAt
        dbUpdatedAt
        scannerDismissedAt
      }
    }
    pageInfo {
      totalObjects
    }
  }
}
