import {Connector} from './connector';
import {
  AirbyteCatalog,
  AirbyteConfig,
  AirbyteMessage,
  AirbyteState,
  ConfiguredAirbyteCatalog,
} from './protocol';

/**
 * Airbyte Source
 * https://docs.airbyte.io/understanding-airbyte/airbyte-specification#source
 */
export abstract class AirbyteSource extends Connector {
  /**
   * @returns An AirbyteCatalog representing the available streams and fields in
   * this integration. For example, given valid credentials to a Postgres
   * database, returns an Airbyte catalog where each postgres table is a stream,
   * and each table column is a field.
   */
  abstract discover(): Promise<AirbyteCatalog>;

  /**
   * @returns A generator of the AirbyteMessages generated by reading the source
   * with the given configuration, catalog, and state.
   */
  abstract read(
    config: AirbyteConfig,
    catalog: ConfiguredAirbyteCatalog,
    state?: AirbyteState
  ): AsyncGenerator<AirbyteMessage>;
}
