query commits($owner: String!, $repo: String!, $branch: String!, $since: GitTimestamp, $until: GitTimestamp, $page_size: Int = 25, $cursor: String) {
  repository(owner: $owner, name: $repo) {
    ref(qualifiedName: $branch) {
      target {
        type: __typename
        ... on Commit {
          history(first: $page_size, after: $cursor, since: $since, until: $until) {
            pageInfo {
              endCursor
              hasNextPage
            }
            nodes {
              ...CommitFields
            }
          }
        }
      }
    }
  }
}
