query projects($login: String!, $cursor: String, $page_size: Int = 100) {
  organization(login: $login) {
    projectsV2(
      first: $page_size
      orderBy: {field: UPDATED_AT, direction: DESC}
      after: $cursor
    ) {
      nodes {
        id
        name: title
        body: shortDescription
        created_at: createdAt
        updated_at: updatedAt
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
