query pullRequestReviewRequests($owner: String!, $repo: String!, $number: Int!, $nested_page_size: Int!, $cursor: String) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $number) {
      reviewRequests(first: $nested_page_size, after: $cursor) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          ...reviewRequestFields
        }
      }
    }
  }
}

