fragment Reviews on PullRequest {
  reviews(first: $nested_page_size, after: $cursor) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      author {
        login
        type: __typename
        ... on Bot {
          html_url: url
        }
        ... on EnterpriseUserAccount {
          name
          html_url: url
        }
        ... on Mannequin {
          html_url: url
        }
        ... on Organization {
          name
          html_url: url
        }
        ... on User {
          name
          html_url: url
        }
      }
      state
      submittedAt
      databaseId
      url
      comments {
        totalCount
      }
    }
    totalCount
  }
}
