query Task(
  $source: String!
  $pageSize: Int
  $offset: Int
  $updatedBefore: timestamptz
  $updatedAfter: timestamptz
  $project: String
) {
  tms_Task(
    where: {
      source: { _eq: $source },
      updatedAt: { _lte: $updatedBefore, _gte: $updatedAfter },
      projects: { project: { uid: { _eq: $project } } }
    },
    limit: $pageSize,
    offset: $offset
  ) {
    uid
    additionalFields
  }
}
