query ProjectBoards(
  $source: String!
  $pageSize: Int
  $offset: Int,
  $projects: [String!]
) {
  tms_Project(
    where: {
      source: { _eq: $source }
      uid: { _in: $projects }
    },
    limit: $pageSize,
    offset: $offset
  ) {
    uid
    boards {
      board {
        uid
      }
    }
  }
}
