connector_image: docker-source
tests:
  spec:
    - config_path: "secrets/config.json"
      spec_path: "resources/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "test_files/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "test_files/full_configured_catalog.json"
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "test_files/full_configured_catalog.json"
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "test_files/incremental_configured_catalog.json"
      future_state_path: "test_files/abnormal_state.json"
      cursor_paths:
        tags: [ "lastCreatedAt" ]
